### PR TITLE
Test Node 4 (newest versions available via nvm)

### PR DESCRIPTION
**Pull request by vielmetti**
Test Node.JS 4.x versions

### CODE REVIEW

**Comment by vielmetti** [comment]
It's failing in 

```
> ✘ t/format/week-iso.t.js: Bail Out!
# TypeError: step is not a function
#     at Object.<anonymous> (/home/travis/build/bigeasy/timezone/node_modules/proof/index.js:107:50)
#     at Object.invoke (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:425:43)
#     at /home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:260:26
#     at Object.starter (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:172:52)
#     at /home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:280:56
#     at Array.forEach (native)
#     at Object.<anonymous> (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:279:37)
#     at Object.invoke (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:439:14)
#     at Object.<anonymous> (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:285:24)
#     at Object.invoke (/home/travis/build/bigeasy/timezone/node_modules/proof/node_modules/cadence/index.js:439:14)
> ✘ t/format/week-iso.t.js: exited with code 1
```

**Comment by bigeasy** [comment]
Proof 0.0.55 has a completely different interface.

**Comment by bigeasy** [comment]
I've completed an upgrade to Proof 0.0.55. It is an ugly upgrade with the minimal edits to make things work, so please do not take it as an example of what Proof is supposed to look like. Any other project would be a better example.

You might want to rebase off `master` and try v4 again.

**Comment by bigeasy** [comment]
This commit shows the specifics of a tidy Proof test.

https://github.com/bigeasy/timezone/commit/1fd4e417143edeb488d256be8c09d0fdb1d6b84b

**Comment by bigeasy** [comment]
Oof! It still has semi-colons.

**Comment by bigeasy** [comment]
Why did this close? It's still not testing against v4.

**Comment by vielmetti** [comment]
Fixed in 2843776ba10310394ffb89656bfdf6fc47feaf92

**Pull request closed without merging**
